### PR TITLE
Added iOS official client

### PR DESCRIPTION
**Pull request by ookangzheng**
I use this client for almost 1 month on ios 11 and 12.
It working fine

### CODE REVIEW

**Comment by angristan** [comment]
Hello! Thanks for the PR.

In the last days, the script has changed a lot, and I implemented OpenVPN 2.4 features. I remember the iOS app not supporting those a while ago.

If possible, could you try with a freshly installed OpenVPN server with the latest version of the script and default parameters? If not, I will wait for someone else's feedback.

**Comment by MartinPC62** [comment]
Hey J'ai le Script de euh Lundi je crois et ça marche ici :)

**Comment by angristan** [comment]
@MartinPC62 Thanks for the feedback. 👍

However I added most of OpenVPN 2.4's features yesterday.

**Comment by ookangzheng** [comment]
okay, I reinstall openvpn and try ~~

**Comment by ookangzheng** [comment]
img_e2dcd5e96982-1
img_53f0f6cec6b6-1
Working fine ~~ on iOS 12 in IphoneSE
Though, I got this error message while I add user on Debian9 vultr VPS
image

**Comment by angristan** [comment]
Thanks 👍

**Comment by angristan** [comment]
I can't reproduce your errors though, but that's another subject

screen shot 2018-09-23 at 20 03 00

**Comment by jellemdekker** [comment]
This pull request can now be closed.

**Pull request merged**
