### PR TITLE
clear user to allow create a new one with the same name

### PR DESCRIPTION
**Pull request by MauricioFesta**

### CODE REVIEW

**Comment by TinCanTech** [comment]
Deleting records from `index.txt` breaks CRL generation.

**Comment by TinCanTech** [comment]
In order to recreate a client of the same name, `index.txt.attr` must be updated.

I have created an issue for this:
https://github.com/OpenVPN/easy-rsa/issues/853

**Comment by angristan** [comment]
Thanks @TinCanTech! Is there a way to handle https://github.com/angristan/openvpn-install/issues/989 until https://github.com/OpenVPN/easy-rsa/issues/853 is tackled?

**Comment by TinCanTech** [comment]
Add `unique_subject = no` to `index.txt.attr`.

Or run command `easyrsa upgrade ca`.
This can be used at any time after `init-pki`.

**Pull request closed without merging**
