### PR TITLE
Initial IPv6 support inside the tunnel for debian and ubuntu

### PR DESCRIPTION
**Pull request by Qwox**
I added some basic IPv6 support for Debian and Ubuntu systems. It works for additional routed subnets, parts of the primary subnet (except debian 7) and NAT for ip6tables (with suitable kernel and ip6tables).

I tested it on different vultr vm's and it runs pretty well. It does not really work on OpenVZ except for a routed subnet maybe, but i dont have such a machine, so i can't test it.

### CODE REVIEW

**Comment by KeiroD** [comment]
Tested the IPv6 addition -- seemed to work ok, but unfortunately I have yet to get it to work successfully, as on the client-side, I'm getting the error:

```
root@EmberLaptop:~# openvpn --config emberlaptop.ovpn 
Sun Nov 12 21:58:23 2017 Unrecognized option or missing parameter(s) in emberlaptop.ovpn:15: block-outside-dns (2.3.10)
Options error: Unrecognized option or missing parameter(s) in emberlaptop.ovpn:20: tls-crypt (2.3.10)
Use --help for more information.
```

**Comment by angristan** [comment]
This is because it uses the 2.4 branch as a base. Use a 2.4 client to support tls-crypt.

**Comment by KeiroD** [comment]
Yep. I'll report back when I've got my vpn client updated to 2.4.

**Comment by ghost** [comment]
Yep. I'll report back when I've got my vpn client updated to 2.4.

**Comment by ghost** [comment]
@Angristan Is this deprecated and the #238 the updated PR? If yes it can be closed, too.

**Comment by angristan** [comment]
They have not the same goal since this is for real IPv6 support and not NAT. But anyway it's too old and would be too hard to manage for now, so I'm closing it

**Pull request closed without merging**
