### PR TITLE
Added openvpn.py

### PR DESCRIPTION
**Pull request by ivica3730k**
Added ability to setup OVPN using Python script. 
Also added ability to use google gmail account to send .OVPN file to end user.
(easier and more secure that to move it to webserver for download)
Ovpn profile will be created based on email account, profile name would be prefix of the email address.

Also updated .gitignore to ignore .ovpn files

### CODE REVIEW

**Comment by TerrorBite** [comment]
I only have one thing to say:

    python openvpn.py --email "-rf /"

**Comment by LouisNitag** [comment]
More fun with this :laughing: 

```python openvpn.py --email "; echo newpassword | passwd --stdin root;"```

**Comment by ghost** [comment]
Lol why close the pr vs update with some proper sanitization?

**Comment by angristan** [comment]
Thank you for your work. This can be useful as a separate wrapper script, but it does not fit the `openvpn-install` project.

**Pull request closed without merging**
