### PR TITLE
Improve sed line deletion

### PR DESCRIPTION
**Pull request by randshell**
https://github.com/angristan/openvpn-install/blob/e123635e7ca50792523ea034bf2ed19749aeb690/openvpn-install.sh#L1131
There is this line too but it's fixed in #604

### CODE REVIEW

**Review by HenryNe — APPROVED** [review]

**Comment by HenryNe** [comment]
> 
> There is this line too but it's fixed in #604

Please change the other line also.
My PR is in draft.

**Review by HenryNe — APPROVED** [review]

**Comment by angristan** [comment]
As usual, please provide justification for your PRs, I cannot guess every time... What do you mean by "fix"? Is it broken? Is it just a better syntax? 

Thanks

**Comment by randshell** [comment]
First is better syntax, second this change deletes the line instead of replacing it with nothing. The difference is that it doesn't leave an empty line between the others lines.

Before:
```
client1

client3
```
After:
```
client1
client3
```

**Comment by angristan** [comment]
Great 👍

**Pull request merged**
