### PR TITLE
OpenVPN 2.4 support

### PR DESCRIPTION
**Pull request by angristan**
This is WIP for adding OpenVPN 2.4 new features into the script

- Add support for AES-GCM ciphers for the data channel
- Add support for tls-crypt
- Add support for ECDSA certificates
- Add support for ECDHE
- Add choice for HMAC auth algorithm
- Add choice for certificate hash algorithm
- Add choice for the control channel's cipher

All these options have an OpenVPN 2.3-compatible choice (example : RSA cert and DH key)

In my previous PR, I removed the encryptions choices to only choose the best ones. Here I've added the choice for every encryption parameter, as it seems that users prefer to use the script this way.

It seems to be working, I'll have to dome some more testing, rewrite some menus and then rewrite the readme with to add the new features.

### CODE REVIEW

**Comment by x0r2d2** [comment]
@Angristan  Please take a look

screenshot 2017-09-14 001

**Comment by angristan** [comment]
Should be fixed now

**Comment by x0r2d2** [comment]
@Angristan 

screenshot 2017-09-14 002

**Comment by x0r2d2** [comment]
@Angristan 

My ISP resets connection, I am in restricted network. 

2.4 branch is working for me - https://github.com/Angristan/OpenVPN-install/blob/openvpn-2.4/openvpn-install.sh

but actual PR is not. 

There are 2 logs in attachment. 

pc1 - current 2.4 branch

client1 - this PR. 

If you need configs, I can attach them also. 

[client1.txt](https://github.com/Angristan/OpenVPN-install/files/1302950/client1.txt)
[pc1.txt](https://github.com/Angristan/OpenVPN-install/files/1302949/pc1.txt)

**Comment by angristan** [comment]
Please update your OpenVPN client.

Also, can you try with a RSA cert, DH key and tls-auth ?

**Comment by x0r2d2** [comment]
@Angristan 
Could you add this  type of TLS-cipher to script, please? 

`TLS-DHE-RSA-WITH-AES-128-GCM-SHA256`

**Comment by angristan** [comment]
Why ?

**Comment by x0r2d2** [comment]
@Angristan 
For test purposes.

I am not good at this. I understand there are to types of OpenVPN now: 

1. 2.3 - Old one, DH, RSA, tls-auth, AES-128/256-CBC
2. 2.4 - New one, ECDHE-ECDSA, elliptic curves, GCM ciphers

Am I right?

**Comment by angristan** [comment]
Well you can add it yourself in the script or directly in your config files

**Comment by x0r2d2** [comment]
@Angristan 
I am trying to figure out, why script from openvpn-2.4 branch is working and script from this PR is not? 
Difference in elliptic curves?

**Comment by angristan** [comment]
I'll try to make some tests on a W10 VM, it's strange indeed

**Comment by x0r2d2** [comment]
@Angristan 
Definitely. the problem is in my network, I mean I need special config to make openvpn work in my network. They are trying to block openvpn tls traffic. 

Thanks for your help. I will be glad to help you in tests.

**Comment by angristan** [comment]
I appreciate your help, but can you please use words, too?

**Comment by x0r2d2** [comment]
@Angristan 
Sorry chief. 
Choose which message digest algorithm.... 2 times mentioned.

**Comment by angristan** [comment]
Thanks, I'm on it

**Comment by x0r2d2** [comment]
@Angristan 
I am unable connect to server. I am trying to understand why. 

Sun Sep 17 18:49:38 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]45.76.35.107:995
Sun Sep 17 18:49:38 2017 Socket Buffers: R=[65536->65536] S=[65536->65536]
Sun Sep 17 18:49:38 2017 Attempting to establish TCP connection with [AF_INET]45.76.35.107:995 [nonblock]
Sun Sep 17 18:49:38 2017 MANAGEMENT: >STATE:1505656178,TCP_CONNECT,,,,,,
Sun Sep 17 18:51:38 2017 TCP: connect to [AF_INET]45.76.35.107:995 failed: Connection timed out (WSAETIMEDOUT)
Sun Sep 17 18:51:38 2017 SIGUSR1[connection failed(soft),init_instance] received, process restarting
Sun Sep 17 18:51:38 2017 MANAGEMENT: >STATE:1505656298,RECONNECTING,init_instance,,,,,
Sun Sep 17 18:51:38 2017 Restart pause, 5 second(s)
Sun Sep 17 18:51:43 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]45.76.35.107:995
Sun Sep 17 18:51:43 2017 Socket Buffers: R=[65536->65536] S=[65536->65536]
Sun Sep 17 18:51:43 2017 Attempting to establish TCP connection with [AF_INET]45.76.35.107:995 [nonblock]
Sun Sep 17 18:51:43 2017 MANAGEMENT: >STATE:1505656303,TCP_CONNECT,,,,,,

**Comment by x0r2d2** [comment]
And maybe this is the reason.

**Comment by angristan** [comment]
What OS ?

**Comment by x0r2d2** [comment]
Ubuntu 16.04

**Comment by x0r2d2** [comment]
So ncp-disable is unknown for Openvpn 2.3.10

**Comment by angristan** [comment]
Yes, it's a OpenVPN 2.4 feature. I didn't realize I forgot to add the 2.4 repo for Ubuntu 16.04, sorry

**Comment by x0r2d2** [comment]
So If I will that feature, service can not bind

**Comment by x0r2d2** [comment]
So, if I will remove local feature, service is starting but I am still unable to connect to server, request timed out.

**Comment by angristan** [comment]
Fixed.

**Comment by angristan** [comment]
After a few hours of testing, I rewrite the compatibility part according to my results.

Now I have to rewrite the Readme to implement all the changes.

**Comment by angristan** [comment]
Btw I forgot to mention in this commit https://github.com/Angristan/OpenVPN-install/pull/96/commits/ff10bd83e67ac6aa8158417b395191e781d1a45c that due to the cipher negotiation, currently when you use the script on the master branch with an OpenVPN 2.4 server and client, you'll use AES-256-GCM whatever there is in the conf.

**Comment by x0r2d2** [comment]
I am still unable to connect to the server with your script. With another script I am able to connect.

**Comment by angristan** [comment]
Then this is certainly a issue on your network...

**Comment by x0r2d2** [comment]
Until this PR, everything was working. Will try it on CentOS

**Comment by angristan** [comment]
Have you tried with the same settings (encryption, ports) ? Also TCP/UDP

**Comment by x0r2d2** [comment]
@Angristan 
Yes, I have tried with the same settings as before. I will check it under different conditions later.

**Comment by x0r2d2** [comment]
@Angristan 
1. Just created clean Ubuntu 16.04 VPS on Vultr. FIrewall turned off. 
2. Used your openvpn-2.4 branch script, everything is OK, I am able to connect. 

> OpenVPN CLIENT LIST
> Updated,Mon Sep 25 04:37:13 2017
> Common Name,Real Address,Bytes Received,Bytes Sent,Connected Since
> client11,95.XX.XX.XX:23459,477091,1409856,Mon Sep 25 04:30:06 2017
> ROUTING TABLE
> Virtual Address,Common Name,Real Address,Last Ref
> 10.8.0.2,client11,95.XX.XX.XX:23459,Mon Sep 25 04:37:11 2017
> GLOBAL STATS
> Max bcast/mcast queue length,0
> END

3. Removing openvpn through your openvpn-2.4 branch script and downloading your openvpn-2.4-update branch script. 
4. Rebooting machine.
5. I am unable to connect, connection timeout. Please find attached the logs. 

Configs almost the same. The difference in cipher and auth algorithm. 

I am not able to find out what is the issue.

[client11.txt](https://github.com/Angristan/OpenVPN-install/files/1328274/client11.txt)
[client111.txt](https://github.com/Angristan/OpenVPN-install/files/1328275/client111.txt)

**Comment by x0r2d2** [comment]
Finally, I were able to connect by removing "local" option of server.conf. 
With this option, service was in failed state. After option removal, service successfully started and I were able to connect to the server.

**Comment by x0r2d2** [comment]
I have created PR https://github.com/Angristan/OpenVPN-install/pull/103
Tested it on my VPS on Vultr, everything is working as should. 
Log attached.
[client.txt](https://github.com/Angristan/OpenVPN-install/files/1328392/client.txt)

**Comment by angristan** [comment]
Thanks ! 😄

**Comment by jellemdekker** [comment]
I see you added a menu to choose a compression algorithm. The README specifies the following: `No comp-lzo, as compression is a vector for oracle attacks, e.g. CRIME or BREACH`. What made you change your mind? And can a user still choose not to enable compression in the menu?

**Comment by angristan** [comment]
@jellemdekker In fact, this does only applies to HTTPS (https://www.pcworld.com/article/262307/crime_attack_abuses_ssltls_data_compression_feature_to_hijack_https_sessions.html). I did not find anything concerning TLS compressions flaws in OpenVPN.

Also: https://security.stackexchange.com/questions/51017/does-the-principle-of-the-crime-beast-attack-affect-vpns

**Comment by Angristan** [comment]
(Exams are over - will work on this soon)

**Comment by jellemdekker** [comment]
@Angristan What is preventing this PR from being merged (aside from the small merge conflict)? Is there anything I can help you implement?

**Comment by HLFH** [comment]
@jellemdekker 

> Is there anything I can help you implement?

https://angristan.fr/soutenir-le-blog/

```text
BTC : 1LdfsyrJhRvN8X3KVJFjxyEsARWNmD2ZtT
ETH : 0x8559064b126196d9ef41685cfc747a7afb91a87a
LTC : LT6GFs32EWX33fHKbN8KPRRXCB8W94AsuH
DOGE : DCXbB66VWLTxaKsnGtWBwyHm7UDL87Sa3M
ZEC : t1YupLKquxaUrZEW3kDPnoZspvzNyCBQdiY
DASH : XuFTWkYrYa9ECrgcGJhshuSUvbycsycvrZ
ETC : 0x5b92fead96fdfde152dd0b142d1033bccef13fd7
DGB : DCGW9j6BCFBsTxg9gP1ZXeb5kC18x4oTrc
MONA : MRU3YjxB7VgNgsMvi6ZpdXFiEisdHtgP8Z
NMC : N5XoTt65J7QUftMEm3LWKrPbWwPdzcucak
VTC : Vsb1JLrtELZNwUBK4Bvvrp41k12y8afZBA
BCH : 1LdfsyrJhRvN8X3KVJFjxyEsARWNmD2ZtT
BTG : GbAoDovMuhsKetSXFbwWjLauCjq296QPFw
```

Sure it will be merged within one working day then.

**Comment by angristan** [comment]
@jellemdekker while the script itself is finished, I still need to rewrite the readme to match the changes. There's nothing anyone can do, I just have to do it... sorry it takes so much time 😅

**Comment by jellemdekker** [comment]
@Angristan No worries, just checking to see if there was anything I could do for you. Take your time, now I know I can use the script that's in this PR. 😃

**Comment by cezar97** [comment]
Tested and everything worked great. There are still some errors in the install by the way.

Apart the `./easyrsa: 644: ./easyrsa: [[: not found` issue, here are the last lines:
```
Note: using Easy-RSA configuration from: ./vars
Using configuration from ./openssl-1.0.cnf

An updated CRL has been created.
CRL file: /etc/openvpn/easy-rsa/pki/crl.pem

sed: no input files
sed: no input files
sed: no input files
408
Synchronizing state of openvpn.service with SysV init with /lib/systemd/systemd-sysv-install...
Executing /lib/systemd/systemd-sysv-install enable openvpn

Finished!
```
Thank You for this Update!

**Comment by angristan** [comment]
Hey @cezar97, what is your hosting provider (or hosting technology)? I can't reproduce on Vultr's KVM

**Comment by cezar97** [comment]
Tried again on Ubuntu Server 16.04 vps (VmWare) and on a Ubuntu Desktop 16.04 pc of mine: same `sed no input files` lines.

**Comment by emilio1625** [comment]
I have some question about how the script is managing iptables and firewalld specially on fedora:
Why it doesn't inform the user that firewalld is going to be disabled and even masked?
Why it doesn't stop the firewalld service?
From line 	[773](https://github.com/Angristan/OpenVPN-install/blob/5a4731f5eada0b2a7705c9ca5da5a8ed74b03a37/openvpn-install.sh#L773)
the changes to iptables are saved, then is checked whether is firewalld active, in fedora, it was not stopped, but on the next reboot it wont be present, and the rules that are passed to firewalld will not be applied on the next reboot.
In the next block where is check "if iptables has at least one REJECT rule" the iptables are never saved, and it makes use of sed to edit something, but i think $RCLOCAL is never declared.
I have this doubts because in my system firewalld is disabled, but not stopped, so the rules for the port work and i can connect, but as soon as i reboot, firewalld is not present anymore, and the rules for the port are not stored in iptables.rules, so i can't connect to the VPN, but it is saved the rule for the NAT. 
Manually adding this
```
iptables -I INPUT -p udp --dport $PORT -j ACCEPT
iptables -I FORWARD -s 10.8.0.0/24 -j ACCEPT
iptables -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables-save > $IPTABLES

```
fixed this problem and even some error messages when uninstalling.
Personally i think completely disabling firewalld and just using iptables would be more convinient.
But i missed something?, maybe I'm not understanding well how the script works, but i'm sure there's an issue there, I'm not uploading a PR because i think i could break something, if i don't understand what i'm i doing and why this is needed
Really sorry for my English

**Comment by angristan** [comment]
@emilio1625 would adding `systemctl stop firewalld` around [here](https://github.com/Angristan/OpenVPN-install/pull/134/files#diff-cda9722285f1718b319bb88e134e9efeR425) fix this?

**Review by ghost — APPROVED** [review]

**Comment by cezar97** [comment]
@Angristan 
https://github.com/Angristan/OpenVPN-install/blob/d165aebe81df1bfb99bf7dc334353e2d5fe4cd1a/openvpn-install.sh#L314-L316
https://github.com/Angristan/OpenVPN-install/blob/d165aebe81df1bfb99bf7dc334353e2d5fe4cd1a/openvpn-install.sh#L452-L454
If RSA is used for OpenVPN 2.3 compatibility ( so $CERT_TYPE = 2 ), then shouldn't the $CC_ENC:
1) have CBC instead of GCM?
2) have not ECDHE?

Correcting these for v2.3 may still lead to a problem: the use of RSA with Elliptic Curves and GCM on v2.4. So the best option is leaving lines 453 and 454 as they are for v2.4 and  for v2.3 adding:
```
echo "Only use AES-CBC for OpenVPN 2.3 compatibilty"
echo "   3) AES-256-CBC"
echo "   4) AES-128-CBC"
```

**Comment by angristan** [comment]
@cezar97 $CC_ENC is Control Channel Encryption. (!= data channel).
OpenVPN 2.3 support ECDHE and AES GCM for the CC, but not the DC.

> Correcting these for v2.3 may still lead to a problem: the use of RSA with ECDHE and GCM on v2.4.

Why is it an issue?

**Comment by cezar97** [comment]
> OpenVPN 2.3 support ECDHE and AES GCM for the CC, but not the DC.

Now it makes sense.
> Correcting these for v2.3 may still lead to a problem: the use of RSA with ECDHE and GCM on v2.4.

It was reffered only if v2.3 didn't supported ECDHE and AES-GCM for CC either.

**Comment by angristan** [comment]
Ok :+1:

**Comment by cezar97** [comment]
Regarding the curves you choosed.
The NIST curves, P-256 (secp256r1), P-384 (secp384r1) and P-521 (secp521r1), are a standard and so they are the most used, but others don't trust them as the curve generation process has unexplained parts.
Here is a more elaborated explanation: http://credelius.com/credelius/?p=97
and technical details about Elliptic Curves and in particular Safe Curves: https://safecurves.cr.yp.to/index.html.
Unfortunately Safe Curves keys generation aren't fully supported by openssl yet, but an alternative that at least has rigidity are the brainpool curves. Why not replace the NIST ones?

**Comment by angristan** [comment]
@cezar97 I already researched the subject and in the end NIST curves were still the best regarding security, speed and support. I agree they aren't the best, but what about client support? `openvpn --show-curves` doesn't work with OpenVPN < 2.4.
But yes this isn't an easy topic.

**Comment by emilio1625** [comment]
Hi, sorry for the late response, i added that line, and that fixed some error messages when installing and uninstalling, but the problem with the iptables not working was not fixed, again, i had to add the ip rules manually, i'll try to fix the issue this week

**Comment by cezar97** [comment]
@Angristan regarding speed NIST curves are the best. Regarding security they haven't rigidity so in fact we don't know for sure if there's any kind of 'backdoor' in the algorithm itself. Regarding support they are the most used and the most common EC curves.
In my previous comment, I was suggesting choosing brainpool ones over the NIST because they have verified rigidity. Regarding speed they are slower than NIST as showed in some online benchmarks. I was thinking of testing them by myself but `openssl speed $1` does not take as argument EC curves, so the only way around this is testing the speed of the network once connected. As hardware I consider doing it on a pi 3b as it's low-end in terms of performance. For support yeah, I was referring only for openvpn > v2.4.
Here the brainpool curves are the best in terms of security that openssl currently supports, until we get support for safe curves of course.
Leaving the topic of NIST security, as for now there are choices between secp256r1, secp384r1 and secp521r1. I was just wondering why `openvpn --show-curves` shows only the Koblitz variant of secp256 and not the random one, so secp256r1.

**Comment by cezar97** [comment]
@Angristan turns out that all the Android clients support only NIST. :neutral_face:

**Comment by mep85** [comment]
Is it possible to add a menu to update an old installation, enable new features, and then re-generate client files based on those preferences?

For example, let's suppose that I upgrade to 2.4 and I want to enable tls-crypt and change cyphers.

Or is the suggested upgrade path just to uninstall and then re-install if changes are desired?

**Comment by cezar97** [comment]
@mep85 To enable tls-crypt you just have to change a line in the config file, the key I think can remain the same. Changing cyphers requires that you regenerate keys and certificates, so it's the same as uninstalling and installing again...

**Comment by x0r2d2** [comment]
@Angristan 
I can not create PR directly to this PR, so I created separate PR for TCP_NODELAY

**Comment by angristan** [comment]
Following https://github.com/Angristan/OpenVPN-install/pull/96#issuecomment-334449467: VORACLE is now a thing. So we will disable compression by default.

https://www.bleepingcomputer.com/news/security/voracle-attack-can-recover-http-data-from-vpn-connections/
https://www.mail-archive.com/openvpn-devel@lists.sourceforge.net/msg16919.html

**Comment by angristan** [comment]
Hello everyone,

Sorry this has taken so long. In the past week, I've worked dozens of hours on the project and rewrote a big part. A lot of features have been added, and a lot of stuff have been improved and fixed.

The master branch is so different than one year ago so this PR is pointless. I added the features one by one on master, and make sure it worked.

The original PR was about one and half year ago... But I finally made it. Also I've improved my skills quite a lot since then so it's not implemented the exact same way.

Anyway, here are the changes:

- Add support for LZ4: https://github.com/angristan/openvpn-install/commit/b898a99485cd552d96e90eac6f14f488618fea8a
- Add support for AES-GCM ciphers for the data channel: https://github.com/angristan/openvpn-install/commit/10a1d04f3bae5fdcf2d7e6ac534c8d326dd61002
- Add support for tls-crypt: https://github.com/angristan/openvpn-install/commit/c2a502be9249bdffde7dcd2286e0bc708e96318c
- Add support for ECDSA certificates: https://github.com/angristan/openvpn-install/commit/4d1baca0c770d2172c288c47b583111562fc654e
- Add support for ECDH: https://github.com/angristan/openvpn-install/commit/3a5e23c5c18cdbed9fb668247105529ce48fd7a4
- Add choice for HMAC auth algorithm: https://github.com/angristan/openvpn-install/commit/bbdabedbec5472404601568ccf94251df8d50a8c
- Add choice for the control channel's cipher: https://github.com/angristan/openvpn-install/commit/4d1baca0c770d2172c288c47b583111562fc654e
- Support _negotiable crypto parameters_ (NCP): https://github.com/angristan/openvpn-install/commit/62c89af95425cc5ca2c062cfa1c11f2be756c82c

Thanks for waiting 🙏

**Comment by angristan** [comment]
Updated the README: https://github.com/angristan/openvpn-install/commit/ba1fc42aacf7a8bda22945ac9e994cde0e948e69

**Pull request closed without merging**
