### PR TITLE
Additions (TLS-Cipher and HMAC Auth)

### PR DESCRIPTION
**Pull request by x0r2d2**
Add:
1. TLS Cipher - TLS-DHE-RSA-WITH-AES-128-GCM-SHA256
2. HMAC_Auth - SHA224

### CODE REVIEW

**Comment by x0r2d2** [comment]
Tls Cipher - TLS-DHE-RSA-WITH-AES-128-GCM-SHA256can be helpful in restricted network like mine. This cipher helps me to connect to my server and maybe will be helpful to other users. 

HMAC_Auth - SHA224 was faster than others. Checked on Asus RT-N11P B1 router with turned on OpenVPN client on Padavan firmware.

**Comment by angristan** [comment]
`TLS-DHE-RSA-WITH-AES-128-GCM-SHA256` was the only one working for you? I don't see why it would change anything, the problem is certainly with your client

**Comment by x0r2d2** [comment]
@Angristan In 2.3 compatibility mode - yes, only this one.

**Comment by angristan** [comment]
What is the version of your client ?

**Comment by x0r2d2** [comment]
2.4.3

**Comment by angristan** [comment]
I don't see why other tls-ciphers wouldn't work 🤔

**Comment by x0r2d2** [comment]
@Angristan 
The addition will not affect the script. I mean, the default parameters are safe and addition of this tls-cipher is only optional, I mean it will be selected by users who needs it.

**Comment by angristan** [comment]
Yes but I don't wand to add it if it's not needed

**Comment by x0r2d2** [comment]
@Angristan 
Anyway, you can reject PR.

**Comment by x0r2d2** [comment]
Added in my fork. 
Closing this PR.

**Pull request closed without merging**
