### PR TITLE
Error exit, afer easyrsa error

### PR DESCRIPTION
**Pull request by HenryNe**
If easyrsa returns an error on creation or revoke client cert, do not continue the rest of script.

### CODE REVIEW

**Comment by HenryNe** [comment]
For simple test:
* Have openvpn-install ready installed
* Start openvpn-install, select "1) Add a new user"
* Entre a name of existing client.
** easy-rsa give an error "Request file already exists", and doeas not create a client
** openvpn-install says "Client test added," and retuns an old cert
* Start openvpn-install, select "2) Revoke existing user"
* Enter a not existing (invalid) number
** easy-rsa give an error
** openvpn-install says "Certificate for client  revoked"
and the exit code is alway 0 (true)

**Comment by TinCanTech** [comment]
> For simple test:
>     * Enter a not existing (invalid) number
>       ** easy-rsa give an error
>       ** openvpn-install says "Certificate for client  revoked"
>       and the exit code is alway 0 (true)

Can you verify that easy-rsa exits with a non-zero error code ?

**Comment by HenryNe** [comment]
> 
> 
> > For simple test:
> > * Enter a not existing (invalid) number
> > ** easy-rsa give an error
> > ** openvpn-install says "Certificate for client  revoked"
> > and the exit code is alway 0 (true)
> 
> Can you verify that easy-rsa exits with a non-zero error code ?

Yes. Run `bash -e -x ./openvpn-install.sh`, Enter `2` for revoke, Enter `99` as inalid number.
The last lines are:

```
+ ./easyrsa --batch revoke ''

Easy-RSA error:

Error: didn't find a file base name as the first argument.
Run easyrsa without commands for usage and command help.
```
The script ends, because easyrsa exits with an error code. It was staretd with "`-e`" for exit on error. The "-x" is to see the executed commands.

**Comment by angristan** [comment]
I took a different approach:
- https://github.com/angristan/openvpn-install/commit/f411d9dec7a0879dd2166573375287130c096166 for revokation
- https://github.com/angristan/openvpn-install/commit/96e6ea71e9094c3b5bce52489e4f8262bb14b16c for creation

**Pull request closed without merging**
