### PR TITLE
Add IPv6 NAT support

### PR DESCRIPTION
**Pull request by angristan**
Thanks to @galaxydata (#236)

**This isn't *real* IPv6 support**, but since it's easy to implement, why not support it?

To do:

- [x] Handle all the firewall stuff
- [x] Detect IPv6 connection on the host before asking
- [x] Choose a cool subnet
- [x] Test on multiple OS and providers
- [x] Update README

Note the connection is made via IPv4 and IPv6 settings are pushed **from** the server

### CODE REVIEW

**Comment by angristan** [comment]
@cezar97 We don't have too, it will work without them, but yes we should do that!

**Comment by 7twin** [comment]
@Angristan this worked just fine on Ubuntu 16.04LTS (the original ipv6 is not leaked anymore)

**Comment by cantalupo555** [comment]
@Angristan Finally support IPv6, thank you!

**Comment by ookangzheng** [comment]
I choose TCP, but the conf file TCP doesn't give me IPV6 version
should be 

```
// TCP ipv6
proto tcp6-server
```
Second,
in the conf file IPv6 part,
It still gives me proto udp6 

Other work fine

**Comment by angristan** [comment]
Ok, it's working.

`ip6tables` won't be applied at boot but I will rework the firewall management after this.

**Pull request merged**
