### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by xiagw**
Simplify some conditions,
Functional,

### CODE REVIEW

**Review by javasboy — COMMENTED** [review]
nice chage,good work!

**Comment by angristan** [comment]
Wow, massive PR!

Not very easy to review considering all the changes and commits 😅

**Comment by stephanerbn** [comment]
Clean! Nice! :D

**Review by zyuiop — APPROVED** [review]

**Comment by angristan** [comment]
What's the point of creating functions for code that's only used once in the script?

**Review by stephanerbn — APPROVED** [review]

**Comment by ghost** [comment]
What's the point of creating functions for code that's only used once in the script?

**Pull request closed without merging**
