### PR TITLE
Add new dns leak tests to FAQ

### PR DESCRIPTION
**Pull request by robiiinos**
Suggested from #633 

Should we specify which of them support IPv6 ?

### CODE REVIEW

**Comment by angristan** [comment]
All of them support IPv6!

**Comment by angristan** [comment]
Sorry, https://dnsleaktest.com/ doesn't.

**Comment by angristan** [comment]
I suppose we should remove `dnsleaktest.com` since it does not support IPv6 and does not provide anything more than the two other alternatives

**Comment by robiiinos** [comment]
Done ! Also specified that both perform IPv4 and IPv6 check, just in case.

**Review by angristan — APPROVED** [review]
Thanks for the contribution 👍

**Pull request merged**
