### PR TITLE
Create openvpndialog.sh

### PR DESCRIPTION
**Pull request by techroy23**
Initial Release
retained original functions except manageusers
main function is not yet link

### CODE REVIEW

**Comment by techroy23** [comment]
i will try to complete the code tommorow

**Comment by techroy23** [comment]
added first 4 steps of install.
sorry im too slow

**Comment by techroy23** [comment]
will try to complete the $installQuestions tommorow.

**Review by angristan — CHANGES_REQUESTED** [review]
Thanks for your interest, but duplicating the code into another script is completely out of the question. 🙁

Also, that's why I wasn't sure about this, it adds a lot of code the script, which is already very heavy.

**Pull request closed without merging**
