### PR TITLE
Custom DNS support and better codes

### PR DESCRIPTION
**Pull request by sayem314**
I have added support for custom DNS and improved overall coding. Also fixed a DNS(9) bug.

### CODE REVIEW

**Comment by angristan** [comment]
Hello, and thank you for your PR.

Could you please explain what does `read -rp` enhances? What about `|| return`?

Also if it doesn't bother you, could you do 2 separate PRs? 🙏

**Comment by jellemdekker** [comment]
1. > Could you please explain what does read -rp enhances?

From the [bash manpage](http://linuxcommand.org/lc3_man_pages/readh.html) about the built-in `read` command:
> -p prompt:	output the string PROMPT without a trailing newline before
    		attempting to read
      -r:		do not allow backslashes to escape any characters



 
2. > What about || return?

From [shellcheck's wiki](https://github.com/koalaman/shellcheck/wiki/SC2164):
> Rationale:
cd can fail for a variety of reasons: misspelled paths, missing directories, missing permissions, broken symlinks and more.
> 
> If/when it does, the script will keep going and do all its operations in the wrong directory. This can be messy, especially if the operations involve creating or deleting a lot of files.
> 
> To avoid this, make sure you handle the cases when cd fails. Ways to do this include
> 
> **cd foo || exit as suggested to just abort immediately**
> if cd foo; then echo "Ok"; else echo "Fail"; fi for custom handling
> <(cd foo && cmd) as an alternative to <(cd foo || exit; cmd) in <(..), $(..) or ( )

Except instead of `cd foo || exit`, it's now `cd foo || return`.

**Comment by jellemdekker** [comment]
@sayem314 Please split up your pull request so that the code for support for custom DNS is in a separate PR.

**Review by angristan — APPROVED** [review]

**Comment by sayem314** [comment]
I’m on vacation for Ramadan. Can’t really make pull request now. I have to update it after Eid. In the meantime if anyone would like to work on that I have no problem with that 🙂 And sorry about real late reply 😔

**Comment by sayem314** [comment]
Closing this in favor of new PR

**Comment by angristan** [comment]
But custom DNS is gone D:

**Comment by sayem314** [comment]
Oh yeah. Forgot about that. Also I broke my wrist 😔

Anyway I will make sure to pull request for custom DNS shortly.

**Pull request closed without merging**
