### PR TITLE
Plaintext cert in ovpn not needed

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by angristan** [comment]
But it could be useful in order get the algorithm or expiration date without using OpenSSL 🤔

**Comment by cezar97** [comment]
I've thought this too, but then I've remembered that there are still the connections logs that shows certs details like the algorithm. For the expiration part, I don't really care as there's enough time.
The PR is because the ovpn looks pretty bad with a pasted plaintext cert in the middle.

**Comment by Angristan** [comment]
I agree, but let's keep following the RFCs as these fields are not optional (even though the are technically)

https://en.wikipedia.org/wiki/X.509#Structure_of_a_certificate

**Comment by cezar97** [comment]
I mean for an end user the certificate details shows in the logs, while the expiration can still be viewed on server side with a `cat` on whatever certificate issued by the sys-admin: no need for openssl.
I didn't get the RFC part, as there is still the certificate in PEM format, just not the plaintext one. It connects anyway, so it's only a "styling" change in the ovpns...

**Comment by angristan** [comment]
I can't resolve conflicts since the original branch does not exist. I added it here: https://github.com/angristan/openvpn-install/commit/8d5d080cc06e10329968b5bd8e85d165fe8321af

Thanks!

**Pull request closed without merging**
