### PR TITLE
Headless installation

### PR DESCRIPTION
**Pull request by cliffcotino**
I've made some small changes to be able to support automatic installation (#261)
It does not support adding a password protected client, or installation behind a NAT, but it's a start.

For installation behind a NAT, the IP detection like could be changed to something like:
`IP=$(wget -q -O - https://api.ipify.org)`

Auto installation command:
```
export APPROVE_INSTALL=y
export APPROVE_IP=y
export IPV6_SUPPORT=n
export PORT_CHOICE=2
export PORT=11194
export PROTOCOL_CHOICE=1
export DNS=9
export COMPRESSION_ENABLED=n
export CUSTOMIZE_ENC=n
export CLIENT=clientName
export PASS=1
./openvpn-install.sh
```

### CODE REVIEW

**Comment by randshell** [comment]
Hi! Thank you for the headless install PR. Indeed it allows for easier reinstall, for example when this script is updated, because it allows to save the variables needed ( we should say it in the README too and maybe ask the user on the first run to export them in a file ) and do its work.

> For installation behind a NAT, the IP detection like could be changed to something like:
 `IP=$(wget -q -O - https://api.ipify.org)`

It should be `$PUBLICIP` instead and so can be exported by the user.
But I don't think using ipify it's a good idea, behind NAT are home users that also have a dynamic IP. In this case the solution is to export the DDNS domain and not use a temporary dynamic IP address to generate the configs.

**Comment by cliffcotino** [comment]
I'll update the README with some instructions how to run the script using a headless install.
I'll see what I can come up with for the option to export it on the first run.

You're right about the `$PUBLICIP` variable, I was thinking about my own use case a bit too much 😃

**Comment by randshell** [comment]
Exporting the variables on first run for easier reinstall was only an idea that for @angristan may be out-of-scope. I was thinking at https://github.com/angristan/openvpn-install/issues/319#issuecomment-449677275 and the related issue. So he decides when he has some free time.

**Comment by cliffcotino** [comment]
@angristan I pushed some documentation on how to use the headless install.
Please let me know if there are other changes you would like to see in this PR

**Comment by angristan** [comment]
Thank you, @cliffcotino.

**Pull request merged**
