### PR TITLE
Merged master into openvpn-2.4-update

### PR DESCRIPTION
**Pull request by vahidshirvani**
* Merged master into openvpn-2.4-update branch and resolved conflicts. I had to this because I wanted to run the script in Ubuntu 18.04. Ubuntu 18.04 did not pass the if statement. 
* I Also changed the order of CloudFlare DNS resolver. Push the primary 1.1.1.1 first.

### CODE REVIEW

**Comment by cezar97** [comment]
Thanks @vahidshirvani !

**Review by ghost — APPROVED** [review]

**Comment by vahidshirvani** [comment]
have merged the master again to include the latest changes and removed the tick from README

**Comment by cezar97** [comment]
Thanks @vahidshirvani. Just wait @Angristan for an official "approve" and maybe merge.
And regarding the tick, I meant that Ubuntu 18.04 is supported and so instead of ❔ it should have ✅ for amd64 at least. Nevermind.

**Comment by vahidshirvani** [comment]
Got it, I have changed the amd64 to green checkbox because that is the only one I tested myself.

**Comment by angristan** [comment]
Thanks for your work, though I'll merge the branches when needed

**Pull request closed without merging**
