### PR TITLE
Backport external IP handling

### PR DESCRIPTION
**Pull request by tvasenin**

### CODE REVIEW

**Comment by angristan** [comment]
May I ask what did you do to backport these specific commits?

**Comment by tvasenin** [comment]
I took the original commits, analyzed what has been done in your repo that could conflict with those changes, and modified the commits accordingly.

Are there any problems with this PR?

**Comment by angristan** [comment]
Oh, no I mean I wonder how do I backport commits from another repo.

**Comment by iProdigy** [comment]
1. add the other repo as remote
2. fetch it
3. git cherry-pick

**Comment by angristan** [comment]
Thanks!

**Pull request merged**
