### PR TITLE
Remove the archlinux part

### PR DESCRIPTION
**Pull request by Kcchouette**
and it should fix the error seen at https://github.com/Angristan/OpenVPN-install/pull/33#issuecomment-282124290

(I've not tested it)

### CODE REVIEW

**Comment by tapir** [comment]
I'll test tomorrow.

**Comment by Kcchouette** [comment]
thanks 😄

**Comment by tapir** [comment]
Works 👍

**Comment by tapir** [comment]
The error is gone but I've noticed another one
```
touch: missing file operand
Try 'touch --help' for more information.
387
```

maybe it was there before, I don't know

**Comment by tapir** [comment]
Ah there is no $SYSCTL anymore and it's trying to touch that

**Comment by Kcchouette** [comment]
indeed @tapir 
Thanks :)

**Comment by angristan** [comment]
Thanks

**Pull request merged**
