### PR TITLE
Add password option for clients

### PR DESCRIPTION
**Pull request by angristan**
This PR adds the option to add a password to the client file. It will be asked when connecting to the OpenVPN server. Basically, this encrypts the client's private key with a password.

Using a password for your private key is more secure, as not having one mean anyone with your .ovpn file can connect to your server and/or decrypt your traffic if they manage to make a MitM.

The user will be given the option when installing the server for the first time (and thus creating the first user) and when adding new users.

### CODE REVIEW

**Comment by angristan** [comment]
Fixes #9 and #159

**Comment by angristan** [comment]
So this is working fine, but atm the password is asked when `./easyrsa` is called. I would like to ask the user for its password first, store it in a variable to use it with easyrsa laster.

**Comment by angristan** [comment]
I was thinking about add `./easyrsa build-client-full $CLIENT <<< $password` but easy-rsa generates the key before asking for the password so it's not possible...

**Comment by jellemdekker** [comment]
_General solution 1: pipes_ in [this Stackoverflow answer](https://stackoverflow.com/a/22422834) might offer some guidance.

**Comment by cezar97** [comment]
Spawn, expect and send may be good options too.
https://askubuntu.com/a/307080

**Comment by PakTam** [comment]
it is possible to create Multiple client using single KEY?
as this website https://sshdropbear.net/

so then the client can be add using WEBMIN or OCS PANEL

**Comment by cezar97** [comment]
@PakTam yes it's possible but this script just doesn't do it because it isn't recommended from a security point of view and this way you can also revoke single users, too.
Anyway I think it's the same certificate rather than the same key.

**Comment by cezar97** [comment]
> So this is working fine, but atm the password is asked when ./easyrsa is called. I would like to ask the user for its password first, store it in a variable to use it with easyrsa later.

Isn't pretty much the same thing writing the pass directly when easyrsa ask so or store it in a variable and use it later for the same thing? What benefits are there in storing it as a variable instead?

**Comment by angristan** [comment]
It's exactly the same except it is more clear to ask for a client password and put it in a variable than having a random prompt in the middle of easy-rsa stuff waiting for something.

**Comment by heikoh81** [comment]
I just installed your script for the first time, thanks!
For use on my mobile phones I'd also prefer to have a scripted Option to ask for a Password.
I figured out how to Change the .sh-file as suggested by craig_mld in #9 
You could say "leave empty if no Password is wanted", but then, it would be easy to add one if needed.

**Comment by fritzmg** [comment]
👍 for this :). Is there any reasony why this isn't merged yet to master?

**Comment by angristan** [comment]
It currently asks the password here:

screenshot_26-05-2018_20-26-08

Does it look acceptable to you?

**Comment by fritzmg** [comment]
Oh I see. Well for me it's good enough, but I understand that it would be more user friendly if it was asked in the beginning.

**Comment by heikoh81** [comment]
When I first used your script about 1-2 month ago, I had to modify the script file as suggested in #9 (remove NOPASS in the code):
https://github.com/Angristan/OpenVPN-install/issues/9
So I now have 2 scripts that I uses: 1 for creating users without password (Raspis) and 1 for users with Passwords (mobile use).

This is very complicated, and thus I suggested you integrate it in your script.
I think the script should state if you leave password empty,  the user is created without password.
I don't see this in the screenshots attached. It just seems to offer the possibility to enter a password - but what happens if none is entered?

**Comment by fritzmg** [comment]
> I don't see this in the screenshots attached. It just seems to offer the possibility to enter a password - but what happens if none is entered?

You can choose whether you want to use a password or not.

**Comment by heikoh81** [comment]
Where is that option? Can't see it in the screenshot?
If I just leave the password blank than there is no password?
(Don't have a Test-system running to test the new version...)

**Comment by cezar97** [comment]
@heikoh81 generally if you put no password then it's generated without one. This script ask if you want a password or not so there's no need to leave it empty when not used.

**Comment by heikoh81** [comment]
Perfect. So that feature I implemented now and no need any more to edit the code yourself?

**Comment by cezar97** [comment]
Well, only when this PR will be merged. Or if you want to speed up things, clone / fork the repo and merge this branch manually into the master. Don't use this branch alone as without merging them both you lose all the new commits on master. @heikoh81

**Comment by heikoh81** [comment]
So let's hope it is merged.
I'm just an advanced enduser, no developer on Github...

**Comment by cezar97** [comment]
@Angristan Instead of leaving PRs open for a long time, especially with this one that has a feature requested by a lot of users, you can `echo "When asked for PEM pass prashe write your password"` so all users know what to do and just merge it. Later you can update it with variables and other suff.
Even if doesn't look acceptable to me either.

**Comment by newsera** [comment]
Can we have this feature implemented for 2.4-update as well?

**Pull request merged**
