### PR TITLE
Update openvpn-install.sh

### PR DESCRIPTION
**Pull request by hadish777**

### CODE REVIEW

**Comment by angristan** [comment]
Hi, can you provide an explanation for this change? I'm not sure I follow. Thanks

**Comment by randshell** [comment]
As far as I know, easy-rsa didn't change the naming of the variables.

**Comment by hadish787** [comment]
Hi there. I just needed to change the name of server in the script.

**Comment by ufukty** [comment]
Line 711 could break the functionality of EasyRSA, if there is no change in variable names. And as I know, `CN` stands for `Common Name` not `Connection` (if `CON` refers to that.)

**Pull request closed without merging**
