### PR TITLE
change mkdir to mkdir -p for directory not exist

### PR DESCRIPTION
**Pull request by cn3lfs**
change mkdir to mkdir -p for directory /etc/openvpn/easy-rsa not exist

### CODE REVIEW

**Comment by randshell** [comment]
What distro are you using that doesn't create `/etc/openvpn`?

**Comment by cn3lfs** [comment]
centos-release-7-3.1611.el7.centos.x86_64. And when I add new openvpn user will encounter error for creating the .ovpn file. in /home/root/someuser.ovpn.



At 2020-06-30 18:37:27, "randomshell" <notifications@github.com> wrote:

What distro are you using that doesn't create /etc/openvpn?

**Comment by randshell** [comment]
We had similar issues in the past, I'm not sure what's wrong. @angristan is going to ask for the debug information so can you please run and paste the output:
```bash
su -
# remove openvpn
./openvpn-install.sh
# install openvpn again with the debug option and paste the full output
bash -x openvpn-install.sh
```
Thanks

---
If you can confirm **everything** works after this modification I think we can include it. It fixes #588, where `/etc/openvpn` didn't exists but openvpn was already installed so the path wasn't going to be created.

I hope it doesn't serve to hide another problem that should be fixed as happened in the past for easy-rsa unpacking. It shouldn't be the case anymore.

**Comment by cn3lfs** [comment]
I tried with your guide. It did works. and not show error for creating directory.And here is the log.
https://gist.github.com/cn3lfs/5414b19639195167172c60535b082af9

**Comment by randshell** [comment]
> If you can confirm everything works after this modification I think we can include it. It fixes #588, where /etc/openvpn didn't exists but openvpn was already installed so the path wasn't going to be created.

Then it looks like this is the case. Thanks @cn3lfs 

As a note, someone suggested "unfinished transactions" to be the problem https://github.com/angristan/openvpn-install/issues/370#issuecomment-450719900 but I wasn't able to reproduce it.

**Review by randshell — APPROVED** [review]
#653 will need an update if this gets merged

**Comment by randshell** [comment]
> when I add new openvpn user will encounter error for creating the .ovpn file.

> change mkdir to mkdir -p for directory /etc/openvpn/easy-rsa not exist

I was thinking that your issue is different than #588. The menu to add a new user is shown when `/etc/openvpn/server.conf` exists, so the folder `/etc/openvpn` exists too and you can create `/etc/openvpn/easy-rsa` without problems. I really don't know what went wrong without the debug ouput, but you said it works now :thinking: 

This PR still fixes issue #588

**Comment by cn3lfs** [comment]
But it now works，whatever. Thanks. I am not very familliar with linux. so let it go any. I amvery happy it can fix others problem.发自我的华为手机-------- 原始邮件 --------主题：Re: [angristan/openvpn-install] change mkdir to mkdir -p for directory not exist (#691)发件人：randomshell 收件人：angristan/openvpn-install 抄送：cn3lfs ,Mention 



when I add new openvpn user will encounter error for creating the .ovpn file.





change mkdir to mkdir -p for directory /etc/openvpn/easy-rsa not exist



I was thinking that your issue is different than #588. The menu to add a new user is shown when /etc/openvpn/server.conf exists, so the folder /etc/openvpn exists too and you can create /etc/openvpn/easy-rsa without problems. I really don't know what went wrong without the debug ouput, but you said it works now 🤔

This PR still fixes issue #588



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/angristan/openvpn-install/pull/691#issuecomment-652611662",

"url": "https://github.com/angristan/openvpn-install/pull/691#issuecomment-652611662",

"name": "View Pull Request"

},

"description": "View this Pull Request on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by angristan** [comment]
Still ok to merge this @randomshell?

**Comment by randshell** [comment]
@angristan The only root cause we found is when OpenVPN is manually installed by the user before running the script https://github.com/angristan/openvpn-install/issues/588#issuecomment-605556142. I don't know how else to reproduce this. So for this specific issue it can be merged.

A clean re-installation using the menu options fixes the other cases, as you already redone the unpacking of Easy-RSA and it shouldn't be a problem anymore.

**Pull request merged**
