### PR TITLE
Updating documentation around existing headless user addition feature

### LINKED ISSUE #422: Add Documentation Around Existing Headless User Addition
Having a headless installer is really great as it allows for instant automation. Well done!

I was looking for an automated way to add new users and about to extend the script before I realised that this functionality is already available.

It may be beneficial to extend the great documentation around automating the addition of users. Somebody else may benefit from that.

Keep up the great work!

### PR DESCRIPTION
**Pull request by dumrauf**
This closes https://github.com/angristan/openvpn-install/issues/422

### CODE REVIEW

**Comment by angristan** [comment]
Still useful after #456?

**Comment by angristan** [comment]
Still useful after #457?

**Comment by dumrauf** [comment]
I'd say that the docs explicitly calling out the headless features are still useful.

Please hold back on merging as I've made some code improvements around headless as well. Seems like there's quite some appetite for that.

**Comment by dumrauf** [comment]
Thanks for your patience. I'm closing this PR in favour of separate PRs.

**Pull request closed without merging**
